<?xml version="1.0" encoding="utf-8"?><Database Name="BD_USER" Class="ConexionUsuariosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-G3SPV0O;Initial Catalog=BD_USER;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="SistemaDeUsuarios.Properties.Settings" SettingsPropertyName="BD_USERConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employee">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Departament" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ActualizarUsuario" Method="ActualizarUsuario">
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SegundoNombre" Parameter="segundoNombre" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Departamento" Parameter="departamento" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Salario" Parameter="salario" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarUsuario" Method="EliminarUsuario">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarUsuario" Method="InsertarUsuario">
    <Parameter Name="PrimerNombre" Parameter="primerNombre" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SegundaNombre" Parameter="segundaNombre" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Departamento" Parameter="departamento" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Salario" Parameter="salario" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LeerUsuarios" Method="LeerUsuarios">
    <ElementType Name="LeerUsuariosResult">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Departament" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>